services:
  backend:
    build: ./backend
    volumes:
      - ./backend/data:/data/sqlite
    env_file:
      - ./backend/.env
    expose:
      - "3001"
    restart: unless-stopped

  frontend:
    build: ./frontend
    env_file:
      - ./backend/.env
    depends_on:
      - backend
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
       - "8080:80"
       - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
      - frontend
    restart: unless-stopped